// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemBiblioteca.Models.Entidades;

#nullable disable

namespace SistemBiblioteca.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    [Migration("20240103153855_Libreria")]
    partial class Libreria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Autor", b =>
                {
                    b.Property<int>("idAutor")
                        .HasColumnType("int")
                        .HasColumnName("idAutor");

                    b.Property<string>("apellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("idAutor")
                        .HasName("PK__autor__5FC3872DFC917D3F");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Categoria", b =>
                {
                    b.Property<int>("idCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<string>("categoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.HasKey("idCategoria")
                        .HasName("PK__categori__CD54BC5AF16FA706");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalleVenta")
                        .HasColumnType("int")
                        .HasColumnName("idDetalleVenta");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdLibro")
                        .HasColumnType("int")
                        .HasColumnName("idLibro");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("idVenta");

                    b.HasKey("IdDetalleVenta")
                        .HasName("PK__detalle___5B265D474B79C795");

                    b.HasIndex("IdLibro");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Editorial", b =>
                {
                    b.Property<int>("IdEditorial")
                        .HasColumnType("int")
                        .HasColumnName("idEditorial");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEditorial")
                        .HasName("PK__editoria__10C1DD0237D2AB48");

                    b.ToTable("Editorial", (string)null);
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .HasColumnType("int")
                        .HasColumnName("idLibro");

                    b.Property<int?>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fechaRegistro");

                    b.Property<int?>("IdAutor")
                        .HasColumnType("int")
                        .HasColumnName("idAutor");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int?>("IdEditorial")
                        .HasColumnType("int")
                        .HasColumnName("idEditorial");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("precio");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlLibro")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("urlLibro");

                    b.HasKey("IdLibro")
                        .HasName("PK__libro__EC09C24E87E2C89D");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEditorial");

                    b.ToTable("Libro", (string)null);
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Roles", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("idRol");

                    b.Property<string>("NombreRol")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreRol");

                    b.HasKey("IdRol")
                        .HasName("PK__roles__C73330E7158EC04F");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Cedula")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("cedula");

                    b.Property<string>("Contasena")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("contasena");

                    b.Property<string>("Correo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("correo");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("idRol");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreUsuario");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario")
                        .HasName("PK__usuario__4E3E04AD30DD6C50");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("idVenta");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("descuento");

                    b.Property<DateTime?>("FechaVenta")
                        .HasColumnType("date")
                        .HasColumnName("fechaVenta");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("iva");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total");

                    b.HasKey("IdVenta")
                        .HasName("PK__ventas__459533BFAE3B2B28");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.DetalleVenta", b =>
                {
                    b.HasOne("SistemBiblioteca.Models.Entidades.Libro", "IdLibroNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdLibro")
                        .HasConstraintName("FK__detalle_v__id_li__48CFD27E");

                    b.HasOne("SistemBiblioteca.Models.Entidades.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("FK__detalle_v__id_ve__47DBAE45");

                    b.Navigation("IdLibroNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Libro", b =>
                {
                    b.HasOne("SistemBiblioteca.Models.Entidades.Autor", "IdAutorNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdAutor")
                        .HasConstraintName("FK__libro__id_autor__49C3F6B7");

                    b.HasOne("SistemBiblioteca.Models.Entidades.Categoria", "IdCategoriaNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__libro__id_catego__398D8EEE");

                    b.HasOne("SistemBiblioteca.Models.Entidades.Editorial", "IdEditorialNavigation")
                        .WithMany("Libros")
                        .HasForeignKey("IdEditorial")
                        .HasConstraintName("FK__libro__id_editor__4AB81AF0");

                    b.Navigation("IdAutorNavigation");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdEditorialNavigation");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Usuario", b =>
                {
                    b.HasOne("SistemBiblioteca.Models.Entidades.Roles", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK_Usuario_Roles");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Venta", b =>
                {
                    b.HasOne("SistemBiblioteca.Models.Entidades.Usuario", "IdUsuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__ventas__id_usuar__44FF419A");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Categoria", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Editorial", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Libro", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Usuario", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SistemBiblioteca.Models.Entidades.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
